// src/app/auth/roles.ts
export const Roles = {
    MARCH: 'ROLE_MARCH',
    DESIGN: 'ROLE_DESIGN',
    FABRIC: 'ROLE_FABRIC',
    CUTTING: 'ROLE_CUTTING',
    SEWING: 'ROLE_SEWING',
    FINISHING: 'ROLE_FINISHING',
    QC: 'ROLE_QC',
    WAREHOUSE: 'ROLE_WAREHOUSE',
    SHIPPING: 'ROLE_SHIPPING'
  };
  